#!/bin/bash
# 03-security.sh - System security hardening
# UFW firewall, fail2ban, SSH hardening, audit tools.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../setup-helpers.sh
source "$SCRIPT_DIR/../setup-helpers.sh"

require_root

log_section "Security Hardening"

# 1. Firewall (UFW)
log_info "Installing firewall (UFW)..."
ensure_pkgs ufw

# Configure firewall (idempotent — ufw handles re-adds gracefully)
ufw --force enable > /dev/null 2>&1 || true
ufw default deny incoming > /dev/null 2>&1 || true
ufw default allow outgoing > /dev/null 2>&1 || true

# Allow SSH (critical — don't lock ourselves out!)
ufw allow 22/tcp > /dev/null 2>&1 || true
# Allow HTTP/HTTPS for development
ufw allow 80/tcp > /dev/null 2>&1 || true
ufw allow 443/tcp > /dev/null 2>&1 || true
log_success "Firewall configured"

# 2. Fail2ban (intrusion prevention)
log_info "Installing fail2ban..."
ensure_pkgs fail2ban

enable_service fail2ban
restart_service fail2ban

# Create local jail config if not exists (idempotent)
if [[ ! -f /etc/fail2ban/jail.local ]]; then
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5
destemail = admin@localhost
sendername = Fail2Ban

[sshd]
enabled = true
maxretry = 3
EOF
    restart_service fail2ban
    log_success "Fail2ban configured"
else
    log_info "Fail2ban configuration already exists"
fi

# 3. SSH Hardening
log_info "Hardening SSH configuration..."

if [[ -f /etc/ssh/sshd_config ]]; then
    # Pre-check: warn if no SSH keys exist (could lock out user)
    if [[ ! -d /root/.ssh ]] || ! ls /root/.ssh/*.pub &>/dev/null; then
        log_warn "┌─────────────────────────────────────────────────────────┐"
        log_warn "│ WARNING: No SSH public keys found for root.            │"
        log_warn "│ Disabling password auth may lock you out of SSH.       │"
        log_warn "│ Ensure SSH keys are set up before the next login.      │"
        log_warn "└─────────────────────────────────────────────────────────┘"
    fi

    # Use a drop-in config for our hardening (cleaner, non-destructive)
    SSHD_HARDENING="/etc/ssh/sshd_config.d/90-debian-setup-hardening.conf"
    if [[ ! -f "$SSHD_HARDENING" ]]; then
        # Back up the main config only on first run (timestamped backups would
        # otherwise pile up on every invocation — we don't even edit this file).
        backup_file /etc/ssh/sshd_config
        cat > "$SSHD_HARDENING" << 'EOF'
# SSH Hardening — generated by debian-setup
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
X11Forwarding no
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
        # Test config before restarting
        if sshd -t > /dev/null 2>&1; then
            restart_service ssh
            log_success "SSH hardened via $SSHD_HARDENING"
        else
            log_error "SSH config test failed — removing hardening file"
            rm -f "$SSHD_HARDENING"
        fi
    else
        log_info "SSH hardening config already exists"
    fi
fi

# 4. File integrity monitoring (AIDE)
log_info "Installing file integrity monitoring (aide)..."
ensure_pkgs aide aide-common

if [[ ! -f /var/lib/aide/aide.db ]]; then
    log_warn "Initializing AIDE database (first run, may take time)..."
    aideinit > /dev/null 2>&1 || true
    # aideinit writes aide.db.new — activate it so the guard above trips next
    # run (otherwise the slow full-filesystem scan repeats on every invocation).
    if [[ -f /var/lib/aide/aide.db.new ]]; then
        mv -f /var/lib/aide/aide.db.new /var/lib/aide/aide.db
        log_success "AIDE database initialized"
    fi
fi

# 5. Audit daemon
log_info "Installing audit daemon..."
ensure_pkgs auditd audispd-plugins

enable_service auditd
restart_service auditd

# 6. Security scanning tools
log_info "Installing security utilities..."
ensure_pkgs \
    lynis \
    chkrootkit \
    rkhunter \
    gnupg

# 7. Automatic security updates
log_info "Installing automatic security updates..."
ensure_pkgs unattended-upgrades apt-listchanges

if [[ -f /etc/apt/apt.conf.d/50unattended-upgrades ]]; then
    append_if_missing \
        /etc/apt/apt.conf.d/50unattended-upgrades \
        "Automatic-Reboot" \
        'Unattended-Upgrade::Automatic-Reboot "false";'
fi

# 8. System limits hardening
log_info "Hardening system limits..."
append_if_missing /etc/security/limits.conf "soft core" \
"# Security hardening — generated by debian-setup
* soft core 0
* hard core 0
* soft nproc 65535
* hard nproc 65535
* soft nofile 65535
* hard nofile 65535"

# 9. Sudo access logging
log_info "Configuring sudo logging..."
if [[ ! -f /etc/sudoers.d/sudo-logging ]]; then
    cat > /etc/sudoers.d/sudo-logging << 'EOF'
Defaults use_pty
Defaults logfile="/var/log/sudo.log"
EOF
    chmod 440 /etc/sudoers.d/sudo-logging
    log_success "Sudo logging configured"
fi

# Clean up
apt-get autoremove -y -qq 2>/dev/null || true
apt-get autoclean -qq 2>/dev/null || true

log_section "Security Hardening Complete"
log_warn "Post-hardening checklist:"
log_warn "  1. Set up SSH key authentication"
log_warn "  2. Run: sudo lynis audit system"
log_warn "  3. Review firewall: sudo ufw status verbose"
log_warn "  4. Monitor: journalctl -u fail2ban -f"
