#!/bin/bash
# 03-security.sh - System security hardening
# UFW firewall, fail2ban, SSH hardening, audit tools.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../setup-helpers.sh
source "$SCRIPT_DIR/../setup-helpers.sh"

require_root

log_section "Security Hardening"

# 1. Firewall (UFW)
log_info "Installing firewall (UFW)..."
ensure_pkgs ufw

# Configure firewall (idempotent — ufw handles re-adds gracefully)
ufw default deny incoming > /dev/null 2>&1 || true
ufw default allow outgoing > /dev/null 2>&1 || true

# Allow SSH (critical — don't lock ourselves out!)
ufw allow 22/tcp > /dev/null 2>&1 || true
# Allow HTTP/HTTPS for development
ufw allow 80/tcp > /dev/null 2>&1 || true
ufw allow 443/tcp > /dev/null 2>&1 || true

# Enable only after the policies and the SSH allow rule are in place, so on a
# remote box the default deny-incoming never briefly severs the session.
ufw --force enable > /dev/null 2>&1 || true
log_success "Firewall configured"

# 2. Fail2ban (intrusion prevention)
log_info "Installing fail2ban..."
ensure_pkgs fail2ban

enable_service fail2ban
restart_service fail2ban

# Create local jail config if not exists (idempotent)
if [[ ! -f /etc/fail2ban/jail.local ]]; then
    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5
destemail = admin@localhost
sendername = Fail2Ban

[sshd]
enabled = true
maxretry = 3
EOF
    restart_service fail2ban
    log_success "Fail2ban configured"
else
    log_info "Fail2ban configuration already exists"
fi

# 3. SSH Hardening
log_info "Hardening SSH configuration..."

if [[ -f /etc/ssh/sshd_config ]]; then
    # Pre-check: warn if the real login user has no SSH keys. PasswordAuthentication
    # is disabled globally below, so a keyless *non-root* user is the one actually at
    # risk of lockout (PermitRootLogin is set to "no" anyway). Prefer $SUDO_USER;
    # otherwise fall back to the first regular account.
    check_user="${SUDO_USER:-}"
    if [[ -z "$check_user" || "$check_user" == "root" ]]; then
        check_user=$(awk -F: '$3 >= 1000 {print $1}' /etc/passwd | grep -v nobody | head -1 || true)
    fi
    check_home=""
    [[ -n "$check_user" ]] && check_home=$(getent passwd "$check_user" | cut -d: -f6 || true)

    keys_found=0
    if [[ -n "$check_home" ]] && ls "$check_home"/.ssh/*.pub &>/dev/null; then
        keys_found=1
    fi
    if ls /root/.ssh/*.pub &>/dev/null; then
        keys_found=1
    fi

    if [[ "$keys_found" -eq 0 ]]; then
        log_warn "WARNING: No SSH public keys found for '${check_user:-<no regular user>}' or root."
        log_warn "This drop-in sets 'PasswordAuthentication no' globally — without a key you"
        log_warn "could be locked out of SSH. Set up keys before your next remote login."
        log_warn "(07-post-installation.sh also generates an ed25519 key for the login user.)"
    fi

    # Use a drop-in config for our hardening (cleaner, non-destructive)
    SSHD_HARDENING="/etc/ssh/sshd_config.d/90-debian-setup-hardening.conf"
    if [[ ! -f "$SSHD_HARDENING" ]]; then
        # Back up the main config only on first run (timestamped backups would
        # otherwise pile up on every invocation — we don't even edit this file).
        backup_file /etc/ssh/sshd_config
        cat > "$SSHD_HARDENING" << 'EOF'
# SSH Hardening — generated by debian-setup
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
X11Forwarding no
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
        # Test config before restarting
        if sshd -t > /dev/null 2>&1; then
            restart_service ssh
            log_success "SSH hardened via $SSHD_HARDENING"
        else
            log_error "SSH config test failed — removing hardening file"
            rm -f "$SSHD_HARDENING"
        fi
    else
        log_info "SSH hardening config already exists"
    fi
fi

# 4. File integrity monitoring (AIDE)
log_info "Installing file integrity monitoring (aide)..."
ensure_pkgs aide aide-common

if [[ ! -f /var/lib/aide/aide.db ]]; then
    log_warn "Initializing AIDE database (first run, may take time)..."
    aideinit > /dev/null 2>&1 || true
    # aideinit writes aide.db.new — activate it so the guard above trips next
    # run (otherwise the slow full-filesystem scan repeats on every invocation).
    if [[ -f /var/lib/aide/aide.db.new ]]; then
        mv -f /var/lib/aide/aide.db.new /var/lib/aide/aide.db
        log_success "AIDE database initialized"
    fi
fi

# 5. Audit daemon
log_info "Installing audit daemon..."
ensure_pkgs auditd audispd-plugins

enable_service auditd
restart_service auditd

# 6. Security scanning tools
log_info "Installing security utilities..."
ensure_pkgs \
    lynis \
    chkrootkit \
    rkhunter \
    gnupg

# 7. Automatic security updates
log_info "Installing automatic security updates..."
ensure_pkgs unattended-upgrades apt-listchanges

if [[ -f /etc/apt/apt.conf.d/50unattended-upgrades ]]; then
    append_if_missing \
        /etc/apt/apt.conf.d/50unattended-upgrades \
        "Automatic-Reboot" \
        'Unattended-Upgrade::Automatic-Reboot "false";'
fi

# 8. System limits hardening
log_info "Hardening system limits..."
append_if_missing /etc/security/limits.conf "soft core" \
"# Security hardening — generated by debian-setup
* soft core 0
* hard core 0
* soft nproc 65535
* hard nproc 65535
* soft nofile 65535
* hard nofile 65535"

# 9. Sudo access logging
log_info "Configuring sudo logging..."
if [[ ! -f /etc/sudoers.d/sudo-logging ]]; then
    cat > /etc/sudoers.d/sudo-logging << 'EOF'
Defaults use_pty
Defaults logfile="/var/log/sudo.log"
EOF
    chmod 440 /etc/sudoers.d/sudo-logging
    log_success "Sudo logging configured"
fi

# 10. Fingerprint reader (fprintd) — only if a reader is present, so machines
# without one don't get a fingerprint prompt/delay at every sudo/login.
log_info "Checking for a fingerprint reader..."
# USB vendor IDs of common readers: Synaptics, Goodix, Elan, AuthenTec,
# Validity, Upek, EgisTec — covers ThinkPad T14 readers.
FP_VENDORS='06cb|27c6|04f3|08ff|138a|147e|1c7a|10a5'
if command_exists lsusb && lsusb 2>/dev/null | grep -qiE "ID (${FP_VENDORS}):"; then
    log_info "Fingerprint reader detected — installing fprintd + PAM integration"
    ensure_pkgs fprintd libpam-fprintd
    # Add fingerprint as an auth option for login/sudo (and the greeter).
    if DEBIAN_FRONTEND=noninteractive pam-auth-update --enable fprintd >/dev/null 2>&1; then
        log_success "Fingerprint PAM enabled (fingerprint OR password)"
    else
        log_warn "Could not auto-enable fprintd in PAM — run: sudo pam-auth-update"
    fi
    log_warn "Enroll YOUR fingerprint (run as your user, not root): fprintd-enroll"
    log_warn "  then test: fprintd-verify   (plain i3lock won't use it — password still works there)"
else
    log_info "No fingerprint reader detected — skipping fprintd"
fi

# Clean up
apt-get autoremove -y -qq 2>/dev/null || true
apt-get autoclean -qq 2>/dev/null || true

log_section "Security Hardening Complete"
log_warn "Post-hardening checklist:"
log_warn "  1. Set up SSH key authentication"
log_warn "  2. Run: sudo lynis audit system"
log_warn "  3. Review firewall: sudo ufw status verbose"
log_warn "  4. Monitor: journalctl -u fail2ban -f"
