#!/bin/bash
# 06-dotfiles.sh - Chezmoi Configuration Manager

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_section() {
    echo -e "\n${BLUE}════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}════════════════════════════════════════${NC}\n"
}

log_section "Dotfiles Setup (Chezmoi)"

# Determine the target user (may be invoked via sudo)
TARGET_USER="${SUDO_USER:-$USER}"
TARGET_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)
if [[ -z "$TARGET_HOME" ]]; then
    TARGET_HOME="$HOME"
fi

if [[ "$EUID" -eq 0 && -z "${SUDO_USER:-}" ]]; then
    log_warn "Running as root without SUDO_USER set — dotfiles will be applied to /root"
fi

if ! command -v chezmoi &> /dev/null; then
    log_info "Installing chezmoi..."
    if command -v curl &> /dev/null; then
        sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
    else
        apt-get update -qq && apt-get install -y -qq chezmoi 2>/dev/null || true
    fi
    log_success "Chezmoi installed"
else
    log_success "Chezmoi already installed"
fi

# Detect which display server / window manager is installed, so chezmoi can
# conditionally skip the irrelevant dotfiles (see home/.chezmoiignore).
_display_server=""
if command -v sway &>/dev/null; then
    _display_server="wayland"
    log_info "Detected Sway/Wayland — applying Wayland dotfiles, skipping X11 configs"
elif command -v i3 &>/dev/null; then
    _display_server="x11"
    log_info "Detected i3/X11 — applying X11 dotfiles, skipping Wayland configs"
else
    log_info "No window manager detected — applying all dotfiles"
fi

# Write chezmoi config with display_server data so .chezmoiignore can use it.
# This is idempotent — safe to overwrite on re-runs.
if [[ -n "$_display_server" ]]; then
    _chezmoi_config_dir="$TARGET_HOME/.config/chezmoi"
    mkdir -p "$_chezmoi_config_dir"
    cat > "$_chezmoi_config_dir/chezmoi.toml" << EOF
# Auto-generated by 06-dotfiles.sh — do not edit manually
[data]
  display_server = "$_display_server"
EOF
    # Fix ownership if running as root
    [[ "$EUID" -eq 0 ]] && chown -R "$TARGET_USER:" "$_chezmoi_config_dir" || true
    log_info "Chezmoi configured: display_server=$_display_server"
fi

log_info "Applying dotfiles from local repository..."
# Run chezmoi as the target user if we're root (to get correct home directory)
if [[ "$EUID" -eq 0 && -n "${SUDO_USER:-}" ]]; then
    sudo -u "$TARGET_USER" chezmoi --source "$REPO_DIR" apply
else
    chezmoi --source "$REPO_DIR" apply
fi

log_success "Dotfiles applied via chezmoi (display_server=${_display_server:-all})"
