#!/bin/bash
# 07-post-installation.sh - Post-installation user configuration
# Sets up user accounts, SSH keys, Git config, Vim plugins.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
# shellcheck source=../setup-helpers.sh
source "$SCRIPT_DIR/../setup-helpers.sh"

# ============================================================================
# Check environment
# ============================================================================
log_section "Post-Installation Setup"

if [[ "$EUID" -eq 0 ]]; then
    RUNNING_AS_ROOT=1
    log_warn "Running as root — will setup system and create user account"
else
    RUNNING_AS_ROOT=0
    CURRENT_USER="$USER"
    log_info "Running as regular user: $CURRENT_USER"
fi

# ============================================================================
# PHASE 1: User Account Setup (root only)
# ============================================================================

if [[ "$RUNNING_AS_ROOT" -eq 1 ]]; then
    log_section "Phase 1: User Account Setup"

    existing_users=$(awk -F: '$3 >= 1000 {print $1}' /etc/passwd | grep -v nobody || true)

    if [[ -z "$existing_users" ]]; then
        log_info "No regular user account found"
        read -rp "Enter username to create: " NEW_USER

        if [[ -z "${NEW_USER:-}" ]]; then
            log_error "Username cannot be empty"
            exit 1
        fi

        if id "$NEW_USER" &>/dev/null; then
            log_warn "User $NEW_USER already exists"
        else
            useradd -m -s /bin/bash "$NEW_USER" || {
                log_error "Failed to create user $NEW_USER"
                exit 1
            }
            log_success "Created user: $NEW_USER"
        fi

        CURRENT_USER="$NEW_USER"
    else
        log_info "Found existing user accounts:"
        echo "$existing_users" | while read -r user; do
            echo "  - $user"
        done
        CURRENT_USER=$(echo "$existing_users" | head -1)
        log_info "Using user: $CURRENT_USER"
    fi

    # Add user to essential groups.
    # video    → webcam access (/dev/video*) for Chromium/WebRTC
    # audio    → USB microphones/headsets and ALSA/PipeWire device access
    # plugdev  → removable/USB devices
    # libvirt/kvm → manage VMs and access /dev/kvm (QEMU/KVM)
    for group in sudo docker libvirt kvm wireshark video audio plugdev; do
        if getent group "$group" &>/dev/null; then
            if ! groups "$CURRENT_USER" | grep -qw "$group"; then
                usermod -aG "$group" "$CURRENT_USER"
                log_success "Added $CURRENT_USER to $group group"
            else
                log_info "$CURRENT_USER already in $group group"
            fi
        fi
    done

    USER_HOME="/home/$CURRENT_USER"
else
    USER_HOME="$HOME"
    log_info "Using home directory: $USER_HOME"
fi

# ============================================================================
# PHASE 2: Shell Configuration
# ============================================================================
log_section "Phase 2: Shell Configuration"

if [[ "$RUNNING_AS_ROOT" -eq 0 ]]; then
    current_shell=$(getent passwd "$CURRENT_USER" | cut -d: -f7)

    if [[ "$current_shell" != "/bin/zsh" ]]; then
        log_info "Current shell: $current_shell"
        if command_exists zsh; then
            read -rp "Change default shell to zsh? (y/n): " ans
            [[ "${ans,,}" == "y" ]] && chsh -s /bin/zsh "$CURRENT_USER" || true
        fi
    else
        log_info "Shell already set to zsh"
    fi
fi

# ============================================================================
# PHASE 3: SSH Key Setup
# ============================================================================
log_section "Phase 3: SSH Key Setup"

SSH_DIR="$USER_HOME/.ssh"
SSH_KEY="$SSH_DIR/id_ed25519"

if [[ -f "$SSH_KEY" ]]; then
    log_info "SSH key already exists: $SSH_KEY"
else
    log_info "Generating SSH key..."

    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
    [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown "$CURRENT_USER:$CURRENT_USER" "$SSH_DIR"

    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "Generated by debian-setup" 2>/dev/null || {
        log_warn "SSH key generation failed"
    }

    if [[ -f "$SSH_KEY" ]]; then
        chmod 600 "$SSH_KEY"
        chmod 644 "$SSH_KEY.pub"
        [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown "$CURRENT_USER:$CURRENT_USER" "$SSH_KEY"*

        log_success "SSH key generated: $SSH_KEY"
        log_info "Public key:"
        cat "$SSH_KEY.pub"
        log_info "Add to: https://github.com/settings/keys"
    fi
fi

# ============================================================================
# PHASE 4: Git Configuration
# ============================================================================
log_section "Phase 4: Git Configuration"

if command_exists git; then
    # Identity goes into ~/.gitconfig.local (git-ignored, included by the tracked
    # ~/.gitconfig). This avoids writing through the symlink into the repo, and
    # keeps the shared config (defaultBranch, pull.rebase, aliases, delta, …) as
    # the single source of truth.
    GITCONFIG_LOCAL="$USER_HOME/.gitconfig.local"

    if [[ "$RUNNING_AS_ROOT" -eq 1 ]]; then
        git_user=$(su - "$CURRENT_USER" -c 'git config user.name' 2>/dev/null || echo "")
    else
        git_user=$(git config user.name 2>/dev/null || echo "")
    fi

    if [[ -z "$git_user" ]]; then
        log_warn "Git user not configured"
        read -rp "Enter Git user name (Enter to skip): " git_name
        read -rp "Enter Git user email (Enter to skip): " git_email

        if [[ -n "${git_name:-}" && -n "${git_email:-}" ]]; then
            git config --file "$GITCONFIG_LOCAL" user.name "$git_name"
            git config --file "$GITCONFIG_LOCAL" user.email "$git_email"
            [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown "$CURRENT_USER:$CURRENT_USER" "$GITCONFIG_LOCAL"
            log_success "Git identity written to $GITCONFIG_LOCAL"
        fi
    else
        log_info "Git already configured: $git_user"
    fi
else
    log_warn "Git is not installed"
fi

# ============================================================================
# PHASE 5: Vim Plugin Setup
# ============================================================================
log_section "Phase 5: Vim Plugin Manager Setup"

VIM_AUTOLOAD_DIR="$USER_HOME/.vim/autoload"
VIM_PLUG_FILE="$VIM_AUTOLOAD_DIR/plug.vim"

if [[ -f "$VIM_PLUG_FILE" ]]; then
    log_info "vim-plug already installed"
else
    log_info "Installing vim-plug..."
    mkdir -p "$VIM_AUTOLOAD_DIR"
    [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown -R "$CURRENT_USER:$CURRENT_USER" "$USER_HOME/.vim"

    curl -fLo "$VIM_PLUG_FILE" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2>/dev/null || {
        log_warn "Failed to download vim-plug"
    }

    if [[ -f "$VIM_PLUG_FILE" ]]; then
        [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown "$CURRENT_USER:$CURRENT_USER" "$VIM_PLUG_FILE"
        log_success "vim-plug installed"
    fi
fi

# ============================================================================
# PHASE 6: Vim Configuration
# ============================================================================
log_section "Phase 6: Vim Configuration and Plugins"

VIMRC_PATH="$USER_HOME/.vimrc"

if [[ -f "$VIMRC_PATH" ]] && grep -q "vim-plug" "$VIMRC_PATH" 2>/dev/null; then
    log_info "Vim already configured with plugins"
else
    log_info "Creating vim configuration..."
    cat > "$VIMRC_PATH" << VIMRC_EOF
" ============================================================================
" VIM Configuration — Auto-generated by debian-setup
" ============================================================================

call plug#begin('${USER_HOME}/.vim/plugged')

" Syntax & Language Support
Plug 'sheerun/vim-polyglot'
Plug 'stephpy/vim-yaml'
Plug 'ekalinin/Dockerfile.vim'

" Git Integration
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" File Explorer & Fuzzy Finder
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Status Bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Linting (includes shellcheck, pylint, etc.)
Plug 'dense-analysis/ale'

" Color Schemes (Catppuccin to match desktop)
Plug 'catppuccin/vim', { 'as': 'catppuccin-vim' }
Plug 'morhetz/gruvbox'

call plug#end()

" ---- Basic Settings ----
set nocompatible
set encoding=utf-8
set number relativenumber
set cursorline ruler showcmd
set autoindent smartindent
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab
set ignorecase smartcase incsearch hlsearch
set wildmenu
set background=dark
silent! colorscheme catppuccin_mocha
syntax enable

" YAML: 2-space indent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2
autocmd FileType dockerfile setlocal ts=2 sts=2 sw=2
autocmd FileType json setlocal ts=2 sts=2 sw=2
autocmd FileType sh setlocal ts=4 sts=4 sw=4

" ---- Key Mappings ----
let mapleader = " "
map <leader>n :NERDTreeToggle<CR>
map <leader>f :NERDTreeFind<CR>
map <leader>p :FZF<CR>
map <leader>b :Buffers<CR>
map <leader>w :w<CR>
map <leader>q :q<CR>

" ---- Plugin Config ----
let g:airline_theme = 'catppuccin_mocha'
let g:airline_powerline_fonts = 1

" ALE linting (replaces syntastic)
let g:ale_linters = {
\   'sh': ['shellcheck'],
\   'python': ['flake8', 'pylint'],
\   'yaml': ['yamllint'],
\   'dockerfile': ['hadolint'],
\}
let g:ale_fix_on_save = 0
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_sh_shellcheck_options = '-x'

" ---- Misc ----
set backspace=indent,eol,start
set laststatus=2
set nobackup nowritebackup noswapfile
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
VIMRC_EOF

    [[ "$RUNNING_AS_ROOT" -eq 1 ]] && chown "$CURRENT_USER:$CURRENT_USER" "$VIMRC_PATH"
    log_success "Vim configuration created (Catppuccin Mocha theme)"
fi

# Install plugins non-interactively
if command_exists vim && [[ -f "$VIMRC_PATH" ]]; then
    log_section "Phase 7: Installing Vim Plugins"
    log_info "Running vim-plug :PlugInstall..."

    if [[ "$RUNNING_AS_ROOT" -eq 1 ]]; then
        # Run as target user so plugins install to their home, not /root/
        su - "$CURRENT_USER" -c "vim -u '$VIMRC_PATH' +PlugInstall +qall" 2>/dev/null || {
            log_warn "Automatic plugin install had issues — run manually as $CURRENT_USER: vim +PlugInstall +qall"
        }
    else
        vim -u "$VIMRC_PATH" +PlugInstall +qall 2>/dev/null || {
            log_warn "Automatic plugin install had issues — run manually: vim +PlugInstall +qall"
        }
    fi
    log_success "Vim plugins installed"
fi

# ============================================================================
# Summary
# ============================================================================
log_section "Post-Installation Complete"

echo -e "${_CLR_GREEN}✓ Configuration Complete!${_CLR_NC}"
echo ""
echo "Configured:"
echo "  ✓ User account & group memberships (incl. video/audio for webcam & mic)"
echo "  ✓ SSH key (ed25519)"
echo "  ✓ Git global config"
echo "  ✓ Vim + plugins (Catppuccin theme)"
echo ""
echo "Vim shortcuts:"
echo "  <Space>n = Toggle NERDTree"
echo "  <Space>p = Fuzzy find files"
echo "  <Space>w = Save | <Space>q = Quit"
echo ""
log_info "Post-installation completed at $(date)"
